name = "TTT_PartnerMod"
author = "Andx"
prefix = "ttt_pm"
mainprefix = "z"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_ttt_pm.png",
    "logo_ttt_pm_ca.paa",
    "LICENSE.md",
    "README.md",
]
exclude = []

[properties]
author = "Andx"
